export interface VideoMetadata {
  videoId: string;
  title: string;
  authorName: string;
  thumbnailUrl: string;
}

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
}

export interface ChatSession {
  id: string;
  title: string;
  model: string;
  messages: ChatMessage[];
  updatedAt: number;
}

export interface GeneratedNotes {
  originalTranscript: string;
  part1: string;
  part2: string;
  part3: string;
  part4: string;
  part5: string;
  zAiAnalysis: string;       // meta/llama-3.3-70b-instruct
  minimaxAnalysis: string;   // nvidia/llama-3.1-nemotron-70b-instruct
  deepseekAnalysis: string;  // deepseek/deepseek-v3
  nemotronAnalysis: string;  // meta/llama-3.1-70b-instruct
  qwenAnalysis: string;      // qwen/qwen-2.5-72b-instruct
  perfectedNotes?: string;   // Final touchup result
}

export interface ShortNotes {
  synthesizedNotes: string;  // synthesized by deepseek/deepseek-v3 & nvidia/llama-3.1-nemotron-70b-instruct
}

export interface PdfDocument {
  pdfContent: string;
  visualPrompt: string;      // generated by nvidia/llama-3.1-nemotron-70b-instruct for flux
  visualImageUrl: string;    // image generated by gemini-2.5-flash-image
}

export enum AppStage {
  INPUT = "INPUT",
  GENERATED_DETAIL = "GENERATED_DETAIL",
  GENERATED_SHORT = "GENERATED_SHORT",
  PDF_COMPILED = "PDF_COMPILED"
}
